services:
  app:
    build: .
    command: npm run start
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres

  postgres:
    build: ./db
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}